### ISSUE TITLE
Running FlowFuse from Synology NAS using Container Manager 

### ISSUE THREAD

**Issue by azrin1972** [FlowFuse/docker-compose#174]
### Current Behavior

I've pulled a docker image "flowfuse/forge-docker" from docker repository 

![image](https://github.com/user-attachments/assets/c6d733cf-3b1d-4895-ad78-648983ae88de)

Then I configure the ports, volume and the environment as below

![image](https://github.com/user-attachments/assets/7dd02aec-76cf-4dfb-a2d7-31108b52542b)

When I Start the container, it immediately stops and this is the log it generates

![image](https://github.com/user-attachments/assets/416b8143-2786-4d74-ad83-47c112d43b7b)

Alternatively, I've tried to follow the manual installation as described in the Installation guide:

download the 2 files:
```
curl -o docker-compose.yml https://raw.githubusercontent.com/FlowFuse/docker-compose/refs/heads/main/docker-compose.yml
curl -o .env https://raw.githubusercontent.com/FlowFuse/docker-compose/refs/heads/main/.env.example
```

I edited the .env file and set the DOMAIN to my registered domain as per my DNS server provider, wildcard has also been enabled in the DNS server.

then executing 

`docker compose -p flowfuse up -d`

gives me 

Please advise
`configs.postgres_db_setup Additional property content is not allowed`

**Comment by hardillb** [comment]
For the manual approach please add a `DBUSER` and `DBPASSWORD` value to the .env file and try again

**Comment by azrin1972** [comment]
> For the manual approach please add a `DBUSER` and `DBPASSWORD` value to the .env file and try again

After adding DBUSER and DBPASSWORD value, now I got this error:
configs.nginx_stream Additional property content is not allowed

**Comment by hardillb** [comment]
the `configs.nginx_stream` should all be commented out, and even if it wasn't the only substitution is for the `DOMAIN` env var.

My gut feel is this is going to be to do with the version of Docker compose available on Synology, but I don't have one to test on.

**Comment by azrin1972** [comment]
I made a mistake, I've set the TLS_ENABLED to "true", but after setting the value back to "", running
`docker-compose -p flowfuse up -d`
gives me this
`configs.nginx Additional property content is not allowed`

**Comment by hardillb** [comment]
again, this is confusing as `configs.nginx` doesn't do any variable substitution, so shouldn't be using properties.

I've just done a fresh local pull and install on debian 11 with docker compose v2.29.7 and it starts with just `DOMAIN` set.

This is making me think it's the docker compose version on the NAS even more.

**Comment by ppawlowski** [comment]
@azrin1972, the `content` property of the `config` field was introduced in Docker Compose `v2.23.1`. Please update the Docker Compose version on your Synology NAS to use our compose file to create the FlowFuse stack.

**Comment by azrin1972** [comment]
Thanks @hardillb 

I'll send a ticket to Synology too for them to check.

I'll keep this issue open for the time being

**Comment by azrin1972** [comment]
> @azrin1972, the `content` property of the `config` field was introduced in Docker Compose `v2.23.1`. Please update the Docker Compose version on your Synology NAS to use our compose file to create the FlowFuse stack.

Ok I will try to update the version and update the result 

Thanks @ppawlowski

**Comment by azrin1972** [comment]
I have a another question

How do I use an external emqx instead?

**Comment by hardillb** [comment]
There is currently no way to use an existing emqx install, the authentication integration is too deep.

You can change the port that the `broker` service binds to so it doesn't clash, e.g. the following would bind the broker to port 1893 rather than 1883

```
...
  broker:
    image: emqx/emqx:5.8.0
    networks:
      - flowforge
    ports:
      - 1893:1883
    healthcheck:
      test: ["CMD", "/opt/emqx/bin/emqx", "ctl", "status"]
      interval: 5s
      timeout: 25s
      retries: 5
    environment:
      - "VIRTUAL_HOST=broker.${DOMAIN:?error},mqtt.${DOMAIN:?error}"
      - "VIRTUAL_PORT=8083"
      - "LETSENCRYPT_HOST=broker.${DOMAIN:?error},mqtt.${DOMAIN:?error}"
      - "EMQX_DASHBOARD__DEFAULT_PASSWORD=topSecret"
    configs:
      - source: emqx
        target: /opt/emqx/data/configs/cluster.hocon
      - source: emqx-api
        target: /mounted/config/api-keys
    volumes:
      - emqx:/opt/emqx/data
...
```
